version: "3.8"

services:
  genesis-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: genesis-server
    ports:
      - "8000:8000"       # Expose genesis server externally
    networks:
      - gbtnetwork

  gbtnode1:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: gbtnode1
    environment:
      - GENESIS_SERVER_URL=http://genesis-server:8000/genesis
      - CHAIN_ID=999
      - SIGNER=0x1a2b3c4d5e6f708192abcdef1234567890abcdef
    ports:
      - "9636:9636"       # RPC exposed
      - "30303:30303"     # P2P TCP
      - "30303:30303/udp" # P2P UDP
    depends_on:
      - genesis-server
    networks:
      - gbtnetwork

networks:
  gbtnetwork:
    driver: bridge
